services:
  - type: web
    name: file-upload-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_ID
        fromSecret: API_ID
      - key: API_HASH
        fromSecret: API_HASH
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
